name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      typedb:
        image: vaticle/typedb:latest
        ports:
          - 1729:1729

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Check Formatting
      run: cargo fmt --all -- --check
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run Tests
      run: cargo test --workspace --verbose
